### PR TITLE
Some tinkering with the rules

### PR DESCRIPTION
**Pull request by DRMacIver**
This started out just wanting to make it clear that the code of
conduct applied online. This resulted in some editing of the opening
paragraph, which resulted in some editing of where in the list things
went, which resulted in me splitting and elaborating on some of the
items.

I think I've largely preserved the original intent. Please tell me if
you think I've screwed up something important.

### CODE REVIEW

**Comment by DRMacIver** [comment]
Confusion caused on IRC BTW: This doesn't confuse formatting changes with text changes. Anywhere I've changed the formatting it was because the edit made the line too long.

**Comment by tef** [comment]
This looks pretty good actually. @ntlk what's your reading of it ?

**Comment by ntlk** [comment]
Looks good to me :+1:

**Comment by russss** [comment]
I'm fine with it. Quick, merge it before everyone else wakes up!

**Comment by public** [comment]
+1

**Comment by doismellburning** [comment]
I like

**Comment by gearmonkey** [comment]
:+1:

**Pull request merged**
