### PR TITLE
add a line about avoiding exclusionary language

### PR DESCRIPTION
**Pull request by DRMacIver**
Attempt to fix issue #158

### CODE REVIEW

**Comment by ntlk** [comment]
I honestly don't feel comfortable with "obey the request"

**Comment by DRMacIver** [comment]
Fair enough. Could you elaborate why / suggest a phrasing you'd be more comfortable with?

**Comment by ntlk** [comment]
I am worried that it will get abused, because it sounds like any request to watch your language must be adhered to. I agree some terms are problematic or hurtful or exclusionary and people should try to not use them if asked, but this line sounds like it goes beyond that.

**Comment by DRMacIver** [comment]
This is why it specifically focuses on "language that people find exclusionary" rather than an arbitrary request to watch your language. Maybe that isn't specific enough?

**Comment by evanmcc** [comment]
I don't have any specific wording suggestions, but maybe a reframing might help.  I've noticed that often people will come at this issue as some sort of compliance issue, a set of rules to be followed and words to be avoided, rather than trying to understand the heart of the issue, which is that language can be hurtful and exclusionary.  The term 'rules lawyer' from the gaming community comes to mind, but I am not sure how best to knock people out of that mindset.

**Comment by russss** [comment]
Hey I think something like this was actually in one of my original code of conduct proposals, but I can't find it now.

My wording was something along the lines of "If someone finds what you say exclusionary, this is not the place to argue about it." Which I still don't find ideal, but it might help.

Edit: and I do have a problem (heh) with the use of the word "obey"

**Comment by tef** [comment]
This seems dogmatic and unhelpful as currently written, as well as long winded. Nb I will say this about most proposed changes. We have a very tight complexity budget, and again i'm all for changes, but we should try and keep to a minimum of words.

I think we can make a better and simpler change, which I've explained in another comment, below

**Comment by tef** [comment]
I suggest change the first line of the existing code to clearly encompass language and behaviour. it already covers jokes and 'ironic' use thereof, so i think it's in scope for this sentence to be updated.

For example:

We want to be inclusive; do not engage in homophobic, racist, transphobic, ableist, sexist, or otherwise exclusionary behavior or language. Don’t make exclusionary jokes, even "ironically". We can teach you better insults that aren't slurs too.

**Comment by tef** [comment]
My current thinking is that we should leave this open for a few days and hammer out the wording, and I imagine that's what @DRMacIver intended. I'd like to get confirmation, especially from organisers before we merge, but as ever I reserve the right to be a BDFL (The B stands for Bad)

**Comment by seubert** [comment]
There has been concern about rules like this negatively policing speech for people that have been the target of certain terms and that use them in a manner of reclamation. I'd prefer to err on the side of less controversial language use, but I am also in a position of privilege here so I don't want to make any policy pushes about it. Just thought I'd mention it since it was definitely brought up in IRC.

**Comment by tef** [comment]
I think it's important to say that the words you use are also covered by behaviour.  Part of why i suggested "We can help you with insults" is because it's hopefully true :-)

**Comment by DRMacIver** [comment]
So the problem is that requests to not use specific words have typically degraded into quite extended arguments about whether those words are OK. In particular "don't use exclusionary language" on its own is not enough, because the problem stems from people not agreeing that specific language usage is exclusionary. This is particularly problematic because it means that people can't trust that a request to not use words that harm them won't make things worse rather than better.

**Comment by DRMacIver** [comment]
P.S. I'm super OK with using any other wording that works and leaving this open until we've hammered out something we're happy with. I've no attachment to my specific choice of words - only the problem in question. I just wanted there to be a concrete proposal out there

**Comment by ntlk** [comment]
I would be okay with another wording

**Comment by tef** [comment]
I am willing to include "This includes language." in the first sentence as something we can include now, and hammer home the details over time. I've also opened a bug because i'm tired of the constant refactoring of the code of conduct.

**Comment by tef** [comment]
I'm going to close this issue and suggest we move discussion into #158. Pull requests need narrow scope.

**Pull request closed without merging**
