### PR TITLE
Add language list for index.html

### PR DESCRIPTION
**Pull request by didlix**

### CODE REVIEW

**Comment by tef** [comment]
Should be same on index.de.html too ?

**Comment by ntlk** [comment]
I can't automagically merge in :(

**Comment by tef** [comment]
And it still doesn't cover the other language pages

**Comment by ntlk** [comment]
@didlix if you update so it can be merged in automatically I will press the big green button :*

**Comment by ntlk** [comment]
Addressed by @drtortoise in https://github.com/computeranonymous/computer/pull/216

**Pull request closed without merging**
