### PR TITLE
Not everyone in London lives or works in Shoreditch

### PR DESCRIPTION
**Pull request by squaremo**
Preemptive strike against Shoreditch hegemony.

### CODE REVIEW

**Comment by russss** [comment]
Heresy!

**Comment by gearmonkey** [comment]
@squaremo: I has kinda thought by labelling an event on the east side of town as 'east london' rather than just 'london' it was, in fact, acknowledging that there are other parts of London.  I mean if you work in say Soho, the venue will take an hour plus to get to. 
So I guess I'm not totally in agreement that things are improved by generalizing the label to all of London, if the venues and meetup are in East London. Demand seems to imply there could be meets in other parts of London, and perhaps that'd be good?
This is to say, I think this group is most useful as a close to where you work (for after work convenience) support hangout, so might it be better to have _multiple_ geographically dispersed London meets?

**Comment by squaremo** [comment]
>  I has kinda thought by labelling an event on the east side of town as 'east london' rather than just 'london'

The label said 'East London', but the file said 'uk_london'.

**Comment by gearmonkey** [comment]
fair. they should clearly agree, either way.

**Comment by squaremo** [comment]
> So I guess I'm not totally in agreement that things are improved by generalizing the label to all of London, if the venues and meetup are in East London. Demand seems to imply there could be meets in other parts of London, and perhaps that'd be good?

That was my thought too. So, now both the label and the filename admit other groups in London.

**Comment by tef** [comment]
@russss you've broken all inbound links by merging this change. please add uk_london back as a placeholder which links to uk_east_london.html

**Pull request merged**
