### PR TITLE
Proposed date/time/location for US/Boston meeting #2: Meadhall

### PR DESCRIPTION
**Pull request by paulswartz**
Per Twitter conversation: https://twitter.com/paulswartz/status/392458890430152705

### CODE REVIEW

**Comment by mattkane218** [comment]
Meadhall can get crowded and loud too, CBC down the street is less so, and they don't mind if you take a table without ordering food! No cocktails though.

**Comment by mattkane218** [comment]
Oh, that is the week after Music Hack Day, I will be recuperating, heh.

**Comment by patcable** [comment]
I can do 14 November. Potentially, I don't necessarily want to conflict with BosOps (https://twitter.com/BosOps) which happens less frequently. I think that's going to be on a Wednesday though.

I'm okay with meadhall, but it can get noisy. It is particularly close to where i live, though :3

**Comment by ntlk** [comment]
Should I merge this is or is it open for discussion?

**Comment by paulswartz** [comment]
I opened it for discussion; I'd wait for a signoff from an actual organizer.

**Comment by decklin** [comment]
I would prefer CBC. Less loud in my experience. Either works though.

**Comment by jimkang** [comment]
I'm also doing Music Hack Day! Anyone else in addition to mkb and me?

Oh, yeah, and to the point: Either venue works for me! 11/14 is good.

**Comment by drtortoise** [comment]
it's been 3 days, maybe time to merge so people coming to the website can see it?

**Comment by darcygarrett** [comment]
Bonnie has a work training event that night and its not a good night for me either, would any other Thursday nights work for people? If not, that's cool, we'll catch you next time!

**Comment by jimkang** [comment]
I make any Thursday in November.

**Comment by paulswartz** [comment]
I'm flexible too.

**Pull request merged**
