### PR TITLE
note in style guide on gendered language

### PR DESCRIPTION
**Pull request by adacable**
B/c there seems to be confusion.

### CODE REVIEW

**Comment by AgentAntelope** [comment]
I'd remove "meatbags" as a little too jokey and replace with "y'all" but :+1:

**Comment by sjmarshy** [comment]
I quite like jokey, keeps it from getting too...serious

**Comment by tef** [comment]
See also Universal Pronouns in english http://personalpages.manchester.ac.uk/staff/andrewkg/ass.final.pdf

**Comment by adacable** [comment]
@AgentAntelope a line above says prefer conversational over bureaucratic.

**Comment by AgentAntelope** [comment]
@drcable fair :)

**Pull request merged**
