### PR TITLE
Fixing bugs with white on black version

### PR DESCRIPTION
**Pull request by adacable**
Fixes bugs:

-You couldn't change back to black on white version once in white
on black.

-Link is now in the colours you'll get if you click it.

### CODE REVIEW

**Comment by tef** [comment]
This can't be merged because acessibility is misspelt. 

Also: I'm not an expert on accessibility so i'd like to have some supporting links and resources to be sure we're doing things in a compliant and standards-friendly way

**Comment by adacable** [comment]
On 29/09/13 23:22, tef wrote:

> This can't be merged because acessibility is misspelt. 
> 
> Also: I'm not an expert on accessibility so i'd like to have some supporting links and resources to be sure we're doing things in a compliant and standards-friendly way 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/computeranonymous/computer/pull/64#issuecomment-25330587
> 
> My bad. Fixing.

## 

---

Thomas Walpole, Maker
drcable.org @drcabl3 drcabl3.tumblr.com

**Comment by adacable** [comment]
Those should be them?

**Comment by adacable** [comment]
Links:
["Web design for dyslexia"](http://www.dyslexia.com/library/webdesign.htm) suggests multipe backgrounc choices, and their own site, cited as best practice, [implements this](http://www.dyslexia.com/customize.htm) among other measures that would start to get really complex to implement.

**Comment by adacable** [comment]
@tef what's holding this up?

**Comment by ntlk** [comment]
@drcable can't merge automatically, and I guess both me and @tef are at work right now

**Comment by adacable** [comment]
Ah, cool.

**Comment by ntlk** [comment]
If you update the PR I can merge in faster :)

On 30 September 2013 at 16:31:59, Thomas Walpole (notifications@github.com) wrote:

Ah, cool.

**Comment by adacable** [comment]
I'm about to leave for femsoc, so can't. Will do when I get home.

**Pull request merged**
