### PR TITLE
Converted whole computer anonymous to use Jekyll

### PR DESCRIPTION
**Pull request by omgmog**
This reduces the overhead of creating new groups pages, means the navigation/header/footer is all in one place, and is just a lot nicer.

I also fixed up a bunch of bad HTML across some of the files, and fixed the 'page jumping around when clicking accessibility' issue

GitHub will handle the processing of the template and pages into actual HTML, so it will work without any hassle. See here: http://pages.github.com/

image

### CODE REVIEW

**Comment by tef** [comment]
Holy Crap!

**Comment by tef** [comment]
This is amazing but I can't auto merge it, can you rebase?

**Comment by ntlk** [comment]
I am impressed

**Comment by tef** [comment]
If you don't have time to rework this, I will try and fix it up once work is finished

**Comment by seubert** [comment]
THANK YOU <3

**Comment by omgmog** [comment]
Hopefully that's more compatible...

**Comment by tef** [comment]
Looks good to me, @ntlk or anyone else want to scan over this?

**Comment by tef** [comment]
:shipit:

**Pull request merged**
