### PR TITLE
Proposing next Austin meeting

### PR DESCRIPTION
**Pull request by lazyatom**
Austin folks - we can use this issue to discuss and finalise date and location for the next meet-up. I've done the simplest thing possible by simply saying the same venue, two weeks later (i.e. Hopfields, on Wednesday 23rd October). Everything is open to change though - please discuss!

Once there's more of a consensus, we can get this merged to make the decision concrete. This will have the neat side effect of also updating the site ;-)

### CODE REVIEW

**Comment by seubert** [comment]
Ahh totally forgot to open this. I'm totally fine with this but understand if people want to change location and/or time. Thanks, James!

**Comment by bkoroleski** [comment]
Hopfields on the 23rd sounds good to me.

**Comment by seubert** [comment]
I think I pinged everyone on Twitter that showed up to first meeting so we might wanna just go forward with this so we can start telling people. @lazyatom, think that's ok?

**Comment by lazyatom** [comment]
It's certainly fine by me, as Hopfields is incredibly convenient, though of course I would be very happy with any venue. I agree that deciding _something_ sooner rather than later is a good thing; I'll edit the title of the pull request.

**Comment by lazyatom** [comment]
@ntlk, @tef, I think this is ready for merge now.

**Comment by williln** [comment]
I am late to this party, but I am game! (Also, I am @laceynwilliams.) 

But can we change the subhead to "Next Meeting" instead of "First Meeting" and combine the two "Time"s so it just says, "Wednesday, October 23, 6pm"? Sorry, I don't know git or how to do a pull request... maybe this is a good chance for me to look up a tutorial and figure it out? Let me know if you think that's ok, and I will do that.

**Comment by seubert** [comment]
@williln If you want you can totally open a PR or I'll do it tomorrow. I'll just do it if I haven't heard from you by the afternoon?
Good git learning resource: http://try.github.io/levels/1/challenges/1

**Pull request merged**
