### PR TITLE
Advice for starting or running a club, now with incident guide #76, github help #94 

### PR DESCRIPTION
**Pull request by tef**
As suggested:
- Remove placeholder link to template code of conduct
- Add Incident Guide to advice for starting a group.
- Move Git volunteers to side page

I think this wraps up a lot of the changes we've wanted to make.

### CODE REVIEW

**Comment by ntlk** [comment]
Shall I just merge or do we need to discuss this further?

**Comment by tef** [comment]
I want a sanity check that I've kept all the bits we wanted. I did leave some bits out as I wasn't happy with the phrasing.

Basically, typos or broken HTML should be fixed, but additions should be another PR

**Comment by tef** [comment]
I think we can add that, but it shouldn't block this.

**Comment by tef** [comment]
added:

<h2>Volunteers</h2>

<p>Try to have more than one point of contact, and if possible try to get people from different groups and backgrounds to volunteer. One person may burn out, and the more diverse the volunteers, the better. </p>

**Comment by tef** [comment]
@ntlk if you're happy, merge :3

**Comment by adacable** [comment]
:+1:

**Pull request merged**
