### PR TITLE
Replace 'brogrammer' reference

### PR DESCRIPTION
**Pull request by doismellburning**
https://github.com/computeranonymous/computer/pull/39 for Reasons

Currently this doesn't replace it with anything; I suspect a replacement clause is needed, but don't know what.

As for Reasons:

From @russss https://github.com/computeranonymous/computer/pull/39#issuecomment-25318944:

> It's clear from this thread that we're not particularly sure how to define "brogramming". I'm increasingly unsure that the people who we want to exclude would identify as "brogrammers" anyway.
> 
> I think the main thing we want to avoid from "brogrammers" is casual sexism. These rules already cover that.

From @tef https://github.com/computeranonymous/computer/pull/39#issuecomment-25321699:

> I'm /mostly/ happy with this commit. I understand why we don't want to use brogrammer/dudebro, but i think we're missing out in that "Boys will be boys" is not welcome, people are expected to be adults and treat each other with respect*

### CODE REVIEW

**Comment by AgentAntelope** [comment]
The link PR was closed because it was agreed that this should be kept, not removed.

**Comment by doismellburning** [comment]
It was? I thought the PR was closed because it was decided that the policy wasn't ready for the removal of http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy (the link referred to in https://github.com/computeranonymous/computer/pull/39#issuecomment-25322287 and such)

**Comment by tef** [comment]
@AgentAntelope  it was agreed that removing it doesn't help right now, but we don't know how to phrase it better.

**Comment by doismellburning** [comment]
(Note I focus wholly on removing the "brogrammer" reference, _not_ the link to the other policy)

**Comment by tef** [comment]
We really don't want to use slang, any more than we want to use jargon. 

As I mentioned in the comments earlier, I'm in favour of removing it, but I'd rather edit it to make it clearer for the behaviours we want and don't want. A simple removal is a loss, but I'm in favour in keeping this PR open to find better language to use.

**Comment by doismellburning** [comment]
@tef Apologies if I wasn't clear - I don't really want this to be merged as-is (i.e. plain removal) - I want an edit, I just don't know what to replace it with; this PR is intended as a place for discussing and proposing replacements.

**Comment by tef** [comment]
We put the link in as a stop gap to explain what we mean by brogrammer. This wasn't meant to endorse the use of the term.

We have removed earlier in-jokes like making fun of HN posters, daily mail readers, and fans of Ayn Rand. I'm happy to continue this precedent because in-jokes backfire horribly.

Edit: Fixed the title of the PR

**Comment by AgentAntelope** [comment]
Given that the slang is now a link explaining the behaviour that the slang refers to, I don't see how removing that and replacing it with text we wrote explaining what we mean instead is better?

**Comment by doismellburning** [comment]
If someone would like to condense the negative behaviour that article describes into a pithy sentence, that'd be a great replacement candidate

**Comment by tef** [comment]
I'd rather not use terms we have to explain, or terms that are english specific and hard to translate into other languages. I'd rather use explicit language which outlines what we find acceptable and unacceptable.

But, brogrammer is the best we have so far, but frankly if we can use clearer language, i will merge it.

**Comment by doismellburning** [comment]
@tef Yep, totally with you - should have been clearer about my "not yet to be merged" intentions!

**Comment by tef** [comment]
Things I want to express:
- This isn't a boys club, or a competition  to be macho. 
- If you tell people to "Man Up", you need to Grow up

**Comment by AgentAntelope** [comment]
also "Real men use $computer_thing" is bad.

**Comment by DRMacIver** [comment]
Commentary copied from IRC:

```
< DRMacIver> The main reason I'm not a fan of brogrammer as a term is that it seems to have a variety of different meanings. Some of them are harmless but seem to get used as a scapegoat. 
< felltir> DRMacIver: that's why I added a link as an improvement
< DRMacIver> felltir: I generally think that when a term has got this confused, trying to clarify its usage doesn't actually help as much as it should. 
< DRMacIver> It's the standards problem. 
< DRMacIver> (http://xkcd.com/927/ that is)
```

I agree about the need to express the points tef wants expressing and I think the decision not to remove brogrammer without replacing it with something else is sensible and good. I just tend to think brogrammer is used as a way of externalising a wider problem and muddies what is actually meant.

**Comment by tef** [comment]
I unfortunately can only think of replacements which involve more slang:

"This isn't a club for boys, nor a place to demonstrate manliness or machismo."

**Comment by ntlk** [comment]
I like that sentence

**Comment by doismellburning** [comment]
@tef I think that sort of slang isn't terrible - I think it's fairly unambiguous, and the "slang" translates well

**Comment by doismellburning** [comment]
```
<li>We think feminism is a good thing. This isn't a club for boys, nor a place to demonstrate manliness or machismo.</li>
```

**Comment by malpinder** [comment]
"isn't a club for boys" implies to me that all men (boys) aren't welcome - it isn't same as "boy's club", alas. I can't think of a better phrasing though. :(

**Comment by doismellburning** [comment]
@rspinder Good point

**Comment by antifuchs** [comment]
Since it seems this should express two sentiments, maybe it should be split in two pieces, entirely:
- This isn't a place to expect or demonstrate manliness.
- Computering isn't a competition.

**Comment by AgentAntelope** [comment]
+1 for "computering isn't a competition." I think that's great.

**Comment by tef** [comment]
I really, really like "Computering isn't a competition" that's brilliant.

**Comment by ntlk** [comment]
"computering isn't a competition" gets a massive upvote from me

**Comment by public** [comment]
I don't like the suggestion that "manliness" is somehow inherently bad but I do like the other thing.

**Comment by tef** [comment]
"This isn't a place to expect or demonstrate aggression—Computering isn't a competition."

**Comment by DRMacIver** [comment]
How about "Isn't a club just for boys"?

**Comment by ntlk** [comment]
"Just" does sound a bit like "but mostly"

**Comment by seubert** [comment]
+1 to tef's line -- covers both aggression and superiority.

**Comment by tef** [comment]
(from code club i can say that most boys are often very very well behaved. Let's not assume these behaviours are limited to children) (hold up is boys ageist?)

**Comment by tef** [comment]
How about:
"This isn't a place to expect or demonstrate aggression or elitism—Computering isn't a competition."

**Comment by doismellburning** [comment]
```
<li>We think feminism is a good thing. This isn't a place to expect or demonstrate aggression or elitism—Computering isn't a competition.</li>
```

**Comment by DRMacIver** [comment]
Suggested edit to tef's statement (which I think is great). Replace "to expect or demonstrate" with "for". i.e.  "This isn't a place for aggression or elitism—Computering isn't a competition."

**Comment by doismellburning** [comment]
@DRMacIver Rolled it in :)

**Comment by gearmonkey** [comment]
"(hold up is boys ageist?)" perhaps, but the bigger problem with calling adult men boys is the history of racism that such behaviour references eg. in the US during Jim Crow and pre-civil war. cf. http://en.wikipedia.org/wiki/Boy#Race

**Comment by gearmonkey** [comment]
also, +1 to "This isn't a place to expect or demonstrate aggression—Computering isn't a competition."

**Comment by doismellburning** [comment]
@gearmonkey Ooh. Ngh :s Good job we've dropped it then!

**Comment by russss** [comment]
I agree with @DRMacIver. I don't think "expect or demonstrate" adds anything.

**Comment by tef** [comment]
Bikeshedding:

This isn't a place to...
"expect or demonstrate"
"expect or behave"
"for"
... aggression or elitism—Computering isn't a competition.

behave makes no grammar i am bad

**Comment by AgentAntelope** [comment]
I think it does. Explicitly saying that you shouldn't expect a behaviour is likely to reassure people who get that behaviour in all other geek spaces.

**Comment by AgentAntelope** [comment]
I vote for option 1 @tef

**Comment by gearmonkey** [comment]
@doismellburning indeed, thought I'd point it out all the same, teach the moment and such.

**Comment by doismellburning** [comment]
I don't feel the "for" loses anything (as per @russss and @DRMacIver)

**Comment by tef** [comment]
"Agression and Elitism are unwelcome here. Computering is not a competition."

**Comment by doismellburning** [comment]
s/Elitism/elitism/ ?

**Comment by tef** [comment]
"Agression and elitism are unwelcome here — computering is not a competition."

edit: no caps

**Comment by doismellburning** [comment]
s/Computering/computer/ ?

**Comment by doismellburning** [comment]
@tef Should be good to go!

**Comment by doismellburning** [comment]
Thanks all

**Pull request merged**
