### PR TITLE
Proposal for weekly meetups until we figure out what days work best.

### PR DESCRIPTION
**Pull request by DRMacIver**
This is definitely a proposal rather than intended to be something computer puts out as official mandate...

I'd just have left this on my personal version of the github pages until it got some sort of interest, but I don't seem to be able to have a github page of this. Computer.

Apologies for moderately awful javascript.

### CODE REVIEW

**Comment by timcowlishaw** [comment]
I really like this. Additionally, I like that a little bit of JS allows people who can't or don't want to grok the algorithm themselves to find out when to attend.

Also, I like that it gives us the opportunity to computer in any given week, rather than only once a month.

Enthusiastic support from me!

**Comment by drtortoise** [comment]
:+1:

**Comment by public** [comment]
I don't like the use of an algorithm to pick a day so that we can meet up enough times to reach consensus on picking more days particularly but weekly meetups while we are still naively enthusiastic about Computer sounds like it might be fun.

Do the days the algorithm picks align such that everyone who's responded on Doodle has at least one option to go to? The density of availability is pretty high so I guess that it quite likely.

**Comment by DRMacIver** [comment]
It isn't picking more days really. It's more highlighting which subset of the days work best. Basically I think that it's all very well having weekly meet-ups, but some are going to be more popular than others and we're probably going to want to have specific meet-ups we recommend new people come to, etc. If it turns out that having weekly events is popular enough this may simply prove unnecessary and we can just keep using the algorithm unvarnished. 

The doodle doesn't have strong enough coverage over the whole month to say if this completely solves the problem, but the algorithm picks two of the most popular days on the doodle (partly by design) and there are definitely a bunch of people who can make it to one but not the other.

**Comment by tef** [comment]
Going to put this on hold until thursday. We'll do an interest check about doing it on the following wednesday

**Comment by timcowlishaw** [comment]
My statistics-sense is twitching at the selection bias involved in polling for interest in a wednesday meeting at a _thursday_ meeting :-)

**Comment by DRMacIver** [comment]
+1 to @timcowlishaw's point. I think the correct polling strategy is to wait until after the first meetup then on the Friday ask on twitter + IRC who would be interested in a second one on Wednesday.

**Comment by DRMacIver** [comment]
I am going to close this for now. I think given the size of the meetup we had last night, weekly meetups are going to be non-viable. I will see if I can come up with a more workable variation on it.

**Pull request closed without merging**
