### PR TITLE
Change north london meetup to not meet in a pub

### PR DESCRIPTION
**Pull request by tef**

### CODE REVIEW

**Comment by adacable** [comment]
:+1:
Ideally meditation space(or similar? ) would have wifi.

**Comment by didlix** [comment]
I don't know, could be interesting to have a ban on technology for a couple of hours?

**Comment by adacable** [comment]
@didlix I object to that in the strongest terms. Technology is part of me.

**Comment by tef** [comment]
I'm open for other computer meetups to set their own rules and expectations. I do not think a laptop/internet ban would be a bad thing. In some ways, it goes back to the name "Computer Anonymous"

**Comment by adacable** [comment]
Which is to say I'll have 3g whatever, but some people won't, and we should cater to them.

**Comment by tef** [comment]
I don't think WiFi is a primary concern of venues.

**Comment by didlix** [comment]
Yeah, the only instrument I know how to play is garage band. I think meditation space with wifi might be hard to find, let's see how it goes.

**Comment by didlix** [comment]
I have changed this so it says north london. I am an idiot and forgot that I am not in west london anymore.

**Comment by adacable** [comment]
Fair enough. I would have significant problems personally with a no-electronics or no-handhelds rule.

**Comment by AgentAntelope** [comment]
I'd be really up for this :D

**Comment by didlix** [comment]
Okay, I see enough interest. Going to merge and look for a venue.

**Comment by doismellburning** [comment]
The commit was still against the West London page...

**Comment by didlix** [comment]
Wait, what.

**Comment by AgentAntelope** [comment]
That's okay, it didn't change it to north london anyhow.

**Comment by didlix** [comment]
Never trust me with anything. I shall fix.

**Comment by didlix** [comment]
computer :: (gh-pages) » g revert 027cc3713dc0d5c0b96f3e667a37aceee4c78157                                                                                         ~/Dropbox/Projects/computer
error: Commit 027cc3713dc0d5c0b96f3e667a37aceee4c78157 is a merge but no -m option was given.
fatal: revert failed
computer :: (gh-pages) » g revert 027cc3713dc0d5c0b96f3e667a37aceee4c78157 -m                                                                                 ~/Dropbox/Projects/computer 128 ↵
error: switch `m' requires a value

Can someone help me git?

**Comment by doismellburning** [comment]
Revert fdffc17a14ea715c78600f9b63ea834fa310e881

**Comment by doismellburning** [comment]
(You'll need to `-m 1`)

**Pull request merged**
