### PR TITLE
Info for October 2014 Boston Meetup

### PR DESCRIPTION
**Pull request by patcable**
@flowerhack is all in NYC doing the hacker school happy fun time, so I am totes making sure that WhyComputer is still a thing. 

(cc: @paulswartz, @haehn, @decklin, @jimkang, @kmbrlynn, @singingwolfboy, @ericwbailey)

### CODE REVIEW

**Comment by flowerhack** [comment]
:confetti_ball: :tropical_drink: :beers: :exclamation: :D

SO EXCITE about this happening

merging this like whoa

**Comment by ericwbailey** [comment]
:star: :pray: :star:

**Comment by patcable** [comment]
:partly_sunny: :volcano: :flashlight:

**Comment by ericwbailey** [comment]
yep

**Pull request merged**
