### PR TITLE
[Denver] Added possible locations and a little more structure

### PR DESCRIPTION
**Pull request by jackflaps**

### CODE REVIEW

**Comment by ntlk** [comment]
If you can make it so I can merge automatically then I will :)

**Comment by jackflaps** [comment]
How do I do that? It's hard to find in the documentation.

**Comment by drtortoise** [comment]
@jackflaps https://help.github.com/articles/syncing-a-fork

**Comment by mjgiarlo** [comment]
@jackflaps If you're short on attention or time, I'd be happy to help out.  Just lemme know.

**Comment by jackflaps** [comment]
@mjgiarlo That'd be great, I still can't figure out what I'm doing.

**Comment by mjgiarlo** [comment]
OK.  See #240.  This issue can be closed now, methinks.

Once that is merged, @jackflaps, you're probably going to want to do something like this locally:

```
git remote add upstream https://github.com/computeranonymous/computer.git 
git fetch upstream
git reset --hard upstream/gh-pages
git push origin gh-pages -f
```

Which will set the state of your local repo and your fork to be synchronized with where the upstream repo is.

**Comment by jackflaps** [comment]
@mjgiarlo thanks! The last two were the steps I wasn't quite sure of.

**Comment by mjgiarlo** [comment]
FWIW, @jackflaps, the way I handled this merge was like so:

```
# Make sure I'm on the right branch
git checkout gh-pages
# Get the latest from upstream
git pull upstream gh-pages
# Point at your repo
git remote add jackflaps https://github.com/jackflaps/computer.git
# Grab your changes
git fetch jackflaps
# Get commit IDs for the two changes you made to us_denver.html
git log
# Pull those commits on top of the latest commit from upstream
git cherry-pick blahblahblah1
git cherry-pick blahblahblah2
# Commit changes
git add us_denver.html
git commit -m "[Denver] adds @negatendo and adds location blahblah"
# Push changes to my GH-based repo
git push origin gh-pages
# Head over to https://github.com/ComputerAnonymousSeattle/computer/compare and issue the pull request
# Done
```

Clearly not git 101 stuff.

**Comment by mjgiarlo** [comment]
You can close this PR now and go "watch" #240, I think.

**Pull request closed without merging**
